name: "Deploy via Rsync"
description: "Adds our private SSH key to the workflow runner so that it can access the remote server"
inputs:
  destination-path:
    description: "Destination path to copy files"
    required: true
  rsync-args:
    description: "Additional arguments to pass to rsync"
    required: false
    default: ""
  rsync-flags:
    description: "Additional flags to pass to rsync"
    required: false
    default: "-avP"
  ssh-host:
    description: "SSH host to use"
    required: true
  ssh-port:
    description: "SSH port to use"
    required: false
    default: 22
  ssh-user:
    description: "SSH user to connect"
    required: false
    default: "piecode"

runs:
  using: "composite"
  steps:
    - name: Check out the Repo
      uses: actions/checkout@v3
    
    - name: Rsync to the remote
      run: rsync ${{inputs.rsync-flags}} --no-perms --no-times --no-owner --delete-after ${{inputs.rsync-args}} . server:${{inputs.destination-path}}
      shell: bash