name: "Add SSH Key"
description: "Adds our private SSH key to the workflow runner so that it can access the remote server"
inputs:
  ssh-host:
    description: "SSH host to use"
    required: true
  ssh-port:
    description: "SSH port to use"
    required: false
    default: 22
  ssh-key:
    description: "SSH key to add"
    required: true

runs:
  using: "composite"
  steps:
    - run: |
            echo "This action was deprecated and may be removed in the future. Please use add-ssh-config instead."
            mkdir -p /home/runner/.ssh
            ssh-keyscan -p ${{ inputs.ssh-port }} ${{ inputs.ssh-host }} >> /home/runner/.ssh/known_hosts
            echo "${{ inputs.ssh-key }}" > /home/runner/.ssh/github_actions
            chmod 600 /home/runner/.ssh/github_actions
            eval "$(ssh-agent -a /tmp/ssh_agent.sock)"
            ssh-add /home/runner/.ssh/github_actions
      shell: bash