name: "Verify Branch is Up-to-date"
description: "Verifies that the branch the workflow is being run upon contains all commits from the target branch"
inputs:
  branch:
    description: "Branch to verify against"
    required: false
    default: main

runs:
  using: "composite"
  steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check if branch contains main
        run: |
          if ! git merge-base --is-ancestor origin/${{inputs.branch}} ${{ github.sha }};
          then echo "This branch is not up to date with main";
          exit 1; fi
        shell: bash