name: Atomic Deploy

on:
  workflow_call:
    inputs:
      ssh-host:
        type: string
        description: "SSH host to connect to"
        required: true
      ssh-user:
        type: string
        description: "SSH user to connect with"
        required: false
        default: piecode
      ssh-port:
        type: number
        description: "SSH port to connect to"
        required: false
        default: 22
      swap-script:
        type: string
        description: "Absolute path to the project's swap.sh on the remote server"
        required: true
      wp-root:
        type: string
        description: "Absolute path to the WordPress root on the remote server"
        required: true
    secrets:
      SSH_PRIVATE_KEY:
        description: "SSH private key"
        required: true

jobs:
  atomic_deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: pie/.github/actions/add-ssh-config@main
        name: Add SSH key to runner
        with:
          ssh-user: ${{inputs.ssh-user}}
          ssh-port: ${{inputs.ssh-port}}
          ssh-host: ${{inputs.ssh-host}}
          ssh-key: ${{secrets.SSH_PRIVATE_KEY}}

      - uses: pie/.github/actions/swap-and-migrate@main
        name: Run atomic swap and migrations
        with:
          swap-script: ${{inputs.swap-script}}
          wp-root: ${{inputs.wp-root}}
          git-sha: ${{github.sha}}
