name: Synchronise Environments

on: 
  workflow_call:
    inputs:
      ssh-port:
        type: number
        description: "SSH port to use"
        required: false
        default: 22
      ssh-user:
        type: string
        description: "SSH user to connect"
        required: false
        default: piecode
      destination-path:
        type: string
        description: "Destination path to remote deployment directory"
        required: true
      rsync-args:
        type: string
        description: "additional arguments to send to rsync"
        required: false
        default: "--no-perms --no-times --no-owner --delete-after"
      rsync-flags:
        type: string
        description: "additional flags to send to rsync"
        required: false
        default: "-avP"
      ssh-host:
        type: string
        description: "SSH host to use"
        required: true
      composer: 
        type: boolean
        description: "Whether to run composer install"
        required: false
        default: false
    secrets:
      SSH_PRIVATE_KEY:
        description: "SSH private key"
        required: true

jobs:
  rsync_to_remote:
    runs-on: ubuntu-latest
    steps:

      - uses: pie/.github/actions/add-ssh-config@main
        name: Add SSH Key to this runner
        with:
          ssh-user: ${{inputs.ssh-user}}
          ssh-port: ${{inputs.ssh-port}}
          ssh-host: ${{inputs.ssh-host}}
          ssh-key: ${{secrets.SSH_PRIVATE_KEY}}

      - uses: pie/.github/actions/deploy-via-rsync@main
        name: Deploying to  ${{inputs.destination-path}} on remote
        with:
          ssh-port: ${{inputs.ssh-port}}
          ssh-host: ${{inputs.ssh-host}}
          ssh-user: ${{inputs.ssh-user}}
          destination-path: ${{inputs.destination-path}}
          rsync-args: ${{inputs.rsync-args}}
          composer: ${{inputs.composer}}
