name: Deploy via Rsync

on: 
  workflow_call:
    inputs:
      ssh-port:
        type: number
        description: "SSH port to use"
        required: false
        default: 22
      ssh-user:
        type: string
        description: "SSH user to connect"
        required: false
        default: piecode
      destination-path:
        type: string
        description: "Destination path to remote deployment directory"
        required: true
      source-path:
        type: string
        description: "Source path to copy files from"
        required: false
        default: "."
      rsync-args:
        type: string
        description: "additional arguments to send to rsync"
        required: false
        default: "--no-perms --no-times --no-owner --delete-after --delete-excluded"
      rsync-flags:
        type: string
        description: "additional flags to send to rsync"
        required: false
        default: "-avP"
      ssh-host:
        type: string
        description: "SSH host to use"
        required: true
      sshpass: 
        type: string
        description: "Whether to deploy using sshpass"
        required: false
        default: "false"
      composer: 
        type: string
        description: "Whether to run composer install"
        required: false
        default: "false"
      npm: 
        type: string
        description: "Whether to run npm install/build"
        required: false
        default: "false"
      npm-run-command:
        type: string
        description: "NPM run command to use"
        required: false
        default: "npm run build"
      node_version:
        type: string
        description: "Node version to use"
        required: false
        default: "18"
    secrets:
      SSH_PRIVATE_KEY:
        description: "SSH private key"
        required: true

jobs:
  rsync_to_remote:
    runs-on: ubuntu-latest
    steps:

      - uses: pie/.github/actions/add-ssh-config@main
        name: Add SSH Key to this runner
        if: ${{ inputs.sshpass == 'false' }}
        with:
          ssh-user: ${{inputs.ssh-user}}
          ssh-port: ${{inputs.ssh-port}}
          ssh-host: ${{inputs.ssh-host}}
          ssh-key: ${{secrets.SSH_PRIVATE_KEY}}

      - uses: pie/.github/actions/add-ssh-pass@main
        name: Add SSH Pass to this runner
        if: ${{ inputs.sshpass != 'false' }}
        with:
          ssh-user: ${{inputs.ssh-user}}
          ssh-port: ${{inputs.ssh-port}}
          ssh-host: ${{inputs.ssh-host}}
          ssh-pass: ${{secrets.SSH_PRIVATE_KEY}}

      - uses: pie/.github/actions/deploy-via-rsync@main
        name: Deploying to  ${{inputs.destination-path}} on remote
        with:
          ssh-port: ${{inputs.ssh-port}}
          ssh-host: ${{inputs.ssh-host}}
          ssh-user: ${{inputs.ssh-user}}
          ssh-pass: ${{secrets.SSH_PRIVATE_KEY}}
          destination-path: ${{inputs.destination-path}}
          source-path: ${{inputs.source-path}}
          rsync-args: ${{inputs.rsync-args}}
          composer: ${{inputs.composer}}
          sshpass: ${{inputs.sshpass}}
          npm: ${{inputs.npm}}
          npm-run-command: ${{inputs.npm-run-command}}
          node_version: ${{inputs.node_version}}
