name: Synchronise Environments

on: 
  workflow_call:
    inputs:
      ssh-host:
        type: string
        description: "SSH host to use"
        required: true
      ssh-port:
        type: number
        description: "SSH port to use"
        required: false
        default: 22
      ssh-user:
        type: string
        description: "SSH user to connect"
        required: true
      destination-path:
        type: string
        description: "Destination path to synchronisation script"
        required: true

jobs:
  sync_remote:
    runs-on: ubuntu-latest
    steps:

      - uses: pie/.github/actions/add-ssh-key@main
        name: Add SSH Key to this runner
        with:
          ssh-port: ${{inputs.ssh-port}}
          ssh-host: ${{inputs.ssh-host}}
          ssh-key: ${{secrets.SSH_PRIVATE_KEY}}

      - uses: pie/.github/actions/synchronise-remote@main
        name: Synchronise remote from Production to Staging
        with:
          ssh-port: ${{inputs.ssh-port}}
          ssh-host: ${{inputs.ssh-host}}
          ssh-user: ${{inputs.ssh-user}}
          destination-path: ${{inputs.destination-path}}
