name: Synchronise Environments

on: 
  workflow_call:
    inputs:
      ssh-host:
        type: string
        description: "SSH host to use"
        required: true
      ssh-port:
        type: number
        description: "SSH port to use"
        required: false
        default: 22
      ssh-user:
        type: string
        description: "SSH user to connect"
        required: true
      synchronisation-script:
        type: string
        description: "Destination path to synchronisation script"
        required: true
    secrets:
      SSH_PRIVATE_KEY:
        description: "SSH private key"
        required: true

jobs:
  sync_remote:
    runs-on: ubuntu-latest
    steps:

      - uses: pie/.github/actions/add-ssh-config@main
        name: Add SSH Key to this runner
        with:
          ssh-port: ${{inputs.ssh-port}}
          ssh-host: ${{inputs.ssh-host}}
          ssh-key: ${{secrets.SSH_PRIVATE_KEY}}

      - uses: pie/.github/actions/synchronise-remote@main
        name: Running ${{inputs.synchronisation-script}} on remote
        with:
          ssh-port: ${{inputs.ssh-port}}
          ssh-host: ${{inputs.ssh-host}}
          ssh-user: ${{inputs.ssh-user}}
          synchronisation-script: ${{inputs.synchronisation-script}}
